### ISSUE TITLE
Figuring things out

### ISSUE THREAD

**Issue by AleMunin** [Retr0ve/website-plugin#1]
Hello! I hope you're having a good day.

I came from the discussion thread on Joplin forums. This is a bit embarrassing, but I'm trying to figure out how this plugin works. I'd like to export my joplin files to an SSG, and the closest thing I know from it is [Stravos' script](https://notes.stavros.io/welcome/stavros-notes/).

How would I make this one work?

**Comment by Retr0ve** [comment]
Hi Ale,
I'm sorry that this is probably not what you are looking for. This repo generates a website for users of Joplin to explore Joplin plugins instead of generating websites from Joplin files. But there might be a plugin for this, like this [one](https://github.com/ylc395/joplin-plugin-pages-publisher).

**Comment by AleMunin** [comment]
Woah, i greatly missed what this project is about. I'm sorry.

Thank you for pointing me into the right direction!
